// Peter F. Drucker quotes, rotated deterministically by date.
// Source books are noted where appropriate; most are from The Effective Executive.
window.DRUCKER_QUOTES = [
  { text: "Until we can manage time, we can manage nothing else.", source: "The Effective Executive" },
  { text: "Know thy time.", source: "The Effective Executive" },
  { text: "Effective executives do not start with their tasks. They start with their time.", source: "The Effective Executive" },
  { text: "Time is the scarcest resource, and unless it is managed nothing else can be managed.", source: "The Effective Executive" },
  { text: "Efficiency is doing things right; effectiveness is doing the right things.", source: "The Effective Executive" },
  { text: "There is nothing so useless as doing efficiently that which should not be done at all.", source: "Managing for Results" },
  { text: "Follow effective action with quiet reflection. From the quiet reflection will come even more effective action.", source: "Peter F. Drucker" },
  { text: "Plans are only good intentions unless they immediately degenerate into hard work.", source: "Peter F. Drucker" },
  { text: "The best way to predict the future is to create it.", source: "Peter F. Drucker" },
  { text: "What gets measured gets managed.", source: "Peter F. Drucker" },
  { text: "Meetings are by definition a concession to deficient organization.", source: "The Effective Executive" },
  { text: "The most important thing in communication is hearing what isn't said.", source: "Peter F. Drucker" },
  { text: "Concentration is the key to economic results.", source: "The Effective Executive" },
  { text: "Effective leadership is not about making speeches or being liked; leadership is defined by results, not attributes.", source: "The Leader of the Future" },
  { text: "Do what you do best and outsource the rest.", source: "Peter F. Drucker" },
  { text: "Unless commitment is made, there are only promises and hopes; but no plans.", source: "Peter F. Drucker" },
  { text: "Results are obtained by exploiting opportunities, not by solving problems.", source: "Managing for Results" },
  { text: "Long‑range planning does not deal with future decisions, but with the future of present decisions.", source: "Peter F. Drucker" },
  { text: "Rank does not confer privilege or give power. It imposes responsibility.", source: "Peter F. Drucker" },
  { text: "Knowledge has to be improved, challenged, and increased constantly, or it vanishes.", source: "Peter F. Drucker" },
  { text: "The only thing we know about the future is that it will be different.", source: "Peter F. Drucker" },
  { text: "Most of what we call management consists of making it difficult for people to get their work done.", source: "Peter F. Drucker" },
  { text: "To manage oneself, learn to manage time.", source: "Managing Oneself" },
  { text: "Whenever you see a successful business, someone once made a courageous decision.", source: "Peter F. Drucker" },
  { text: "The productivity of work is not the responsibility of the worker but of the manager.", source: "Peter F. Drucker" },
  { text: "Strategy is a commodity, execution is an art.", source: "Peter F. Drucker" },
  { text: "Doing the right thing is more important than doing the thing right.", source: "The Effective Executive" },
  { text: "The first rule of decision‑making is that one does not make a decision unless there is disagreement.", source: "The Effective Executive" },
  { text: "Effectiveness is a habit; that is, a complex of practices. And practices can always be learned.", source: "The Effective Executive" },
  { text: "The executive who records and analyses his use of time and then attempts to manage it, is the exception.", source: "The Effective Executive" },
  { text: "Time is the one resource that cannot be stored or replaced.", source: "The Effective Executive" },
  { text: "Working on the right things is what makes knowledge work effective.", source: "The Effective Executive" },
  { text: "The effective executive focuses on contribution — on what can I do to make a significant difference?", source: "The Effective Executive" },
  { text: "All one can think and do in a short time is to think what one already knows and to do as one has always done.", source: "The Effective Executive" },
  { text: "Make strength productive. Weaknesses are irrelevant; strength is what produces results.", source: "The Effective Executive" },
  { text: "First things first — and second things not at all.", source: "The Effective Executive" }
];
